#!/bin/sh

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

# dmenu_run -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"
dmenu_recency -l 10 -i -p "Select:" -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"
