#!/bin/bash
# originally by Kris Occhipinti
# tweaked by Rituraj

if [ $# -eq 0 ]
then
  LINK=$(xclip -selection clipboard -o)
else
  LINK=$1
fi

TITLE=$(youtube-dl --get-title "$LINK")
# notify-send -t 3000 --app-name="MPV" "Playing Video" "$TITLE";
dunstify -t 3000 -u low -i multimedia-video-player -a "MPV" "Playing Video" "$TITLE";
mpv --script=~/.config/mpv/scripts/mpris.so --ytdl-format="[height<=?1080]" --speed=1.65 "$LINK" &

