#!/bin/bash
# originally by Kris Occhipinti
# tweaked by Rituraj

if [ $# -eq 0 ]
then
  LINK=$(xclip -selection clipboard -o)
else
  LINK=$1
fi

TITLE=$(youtube-dl --get-title "$LINK")
# TITLE="Playing Video"
notify-send -t 3000 --app-name="MPV" "Playing Video" "$TITLE";
mpv --script=~/.config/mpv/scripts/mpris.so --ytdl-format="[height<=?1080]" --speed=1.65 "$LINK" &

# TITLE=$(playerctl --player mpv metadata -f "{{xesame:title}}")
# notify-send -t 3000 --app-name="MPV" "Playing Video" "$TITLE";

